.pragma library

const leftArrow = "qrc:/icons/arrow-thick-left.svg"
const rightArrow = "qrc:/icons/arrow-thick-right.svg"
const book = "qrc:/icons/book.svg"
const check = "qrc:/icons/check.svg"
const chevronRight = "qrc:/icons/chevron-right.svg"
const code = "qrc:/icons/code.svg"
const cog = "qrc:/icons/cog.svg"
const folder = "qrc:/icons/folder.svg"
const info = "qrc:/icons/info.svg"
const list = "qrc:/icons/list.svg"
const loopCircular = "qrc:/icons/loop-circular.svg"
const magnifyingGlass = "qrc:/icons/magnifying-glass.svg"
const menu = "qrc:/icons/menu.svg"
const pencil = "qrc:/icons/pencil.svg"
const plus = "qrc:/icons/plus.svg"
const questionMark = "qrc:/icons/question-mark.svg"
const share = "qrc:/icons/share.svg"
const spreadsheet = "qrc:/icons/spreadsheet.svg"
const trash = "qrc:/icons/trash.svg"
const warning = "qrc:/icons/warning.svg"
