name: "Install cmake, ninja, conan, qt."

inputs:
  qt-version:
    default: 6.4.2

  conan-version:
    default: 1.59.0

runs:
  using: "composite"
  steps:
    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest

    - name: Install Conan package manager
      uses: turtlebrowser/get-conan@main
      with:
        version: ${{ inputs.conan-version }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: ${{ inputs.qt-version }}
        dir: ${{ github.workspace }}
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true
