name: "Install cmake, ninja, conan, qt."

inputs:
  qt-version:
    type: string
    required: true

  conan-version:
    default: 1.59.0

  install-wasm-deps:
    default: false

  emsdk-version:
    type: string

  aqtversion:
    default: ==3.1.5

  py7zrversion:
    default: ==0.20.2

runs:
  using: "composite"
  steps:
    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest

    - name: Install Conan package manager
      uses: turtlebrowser/get-conan@main
      with:
        version: ${{ inputs.conan-version }}

    - name: Install Qt gcc_64
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: ${{ inputs.aqtversion }}
        py7zrversion: ${{ inputs.py7zrversion }}
        version: ${{ inputs.qt-version }}
        dir: ${{ github.workspace }}
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - if: ${{ inputs.install-wasm-deps }}
      name: Install Emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: ${{ inputs.emsdk-version }}
        no-cache: true

    - if: ${{ inputs.install-wasm-deps }}
      name: Install Qt wasm multithread
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: ${{ inputs.aqtversion }}
        py7zrversion: ${{ inputs.py7zrversion }}
        version: ${{ inputs.qt-version }}
        dir: ${{ github.workspace }}
        arch: 'wasm_32'
        # arch: 'wasm_singlethread' For 6.5.0 version
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true
