name: "Install cmake, ninja, conan, qt."

runs:
  using: "composite"
  steps:
    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest

    - name: Install Conan package manager
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0
