name: "Install cmake, ninja, conan, qt."

inputs:
  qt-version:
    type: string
    default: 6.4.2

  conan-version:
    type: string
    default: 1.59.0

  install-emsdk:
    default: false

  emsdk-version:
    type: string
    default: 3.1.14

outputs:
  qt-version:
    value: ${{ inputs.qt-version }}
    type: string

runs:
  using: "composite"
  steps:
    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest

    - name: Install Conan package manager
      uses: turtlebrowser/get-conan@main
      with:
        version: ${{ inputs.conan-version }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ inputs.qt-version }}
        dir: ${{ github.workspace }}
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - if: ${{ inputs.install-emsdk }}
      name: Install Emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: ${{ inputs.emsdk-version }}
        no-cache: true
