name: "prepare_build_env"
description: "Prepares build environment. Install cmake, ninja, conan, qt."

runs:
  using: "composite"
  steps:
    - name: Install Conan package manager
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0
