name: Application build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.4.2
  WASM_VERSION: 3.1.14
  QT_ROOT: ${{ github.workspace }}/Qt

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        build_profile: [desktop_dev, desktop_release, wasm_release]

    concurrency:
      group: AppBuild-${{ github.workflow }}-${{ github.ref }}-${{ matrix.build_profile }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest

    - uses: ./.github/workflows/PrepareBuildEnvironment.yml

    - if: ${{ matrix.build_profile == 'wasm_release' }}
      name: Install Wasm
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.WASM_VERSION }}
        actions-cache-folder: 'emsdk-cache'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: ${{ env.QT_VERSION }}
        dir: ${{ github.workspace }}
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - if: ${{ matrix.build_profile == 'wasm_release' }}
      name: Cache Multithread qt wasm
      id: cache-mt-wasm
      uses: actions/cache@v3
      with:
        key: ${{ env.QT_VERSION }}-wasm_32_mt
        path: ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/wasm_32_mt

    - if: ${{ matrix.build_profile == 'wasm_release' && steps.cache-mt-wasm.outputs.cache-hit != 'true' }}
      name: Build multithread Qt wasm
      run: ./project.py --build QtWasmMultithread

    - name: Conan install dependencies
      working-directory: ${{github.workspace}}/apps/Application
      run: conan install . --profile conanfiles/profile/${{ matrix.build_profile }} --build=missing -if=build/${{ matrix.build_profile }}/conan-dependencies

    - name: CMake configure
      working-directory: ${{github.workspace}}/apps/Application
      run: cmake --preset ${{ matrix.build_profile }} ./

    - name: Cmake build
      working-directory: ${{github.workspace}}/apps/Application
      run: cmake --build --preset ${{ matrix.build_profile }}

    - if: ${{ matrix.build_profile != 'wasm_release' }}
      name: CTest
      working-directory: ${{github.workspace}}/apps/Application
      run: ctest --preset ${{ matrix.build_profile }}
