name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: |
          sudo apt install ninja-build
          pip install conan

    - uses: actions/checkout@v3

    - name: Conan install
      run: |
        cd apps/TermGraphApp/
        conan install . --profile conanfiles/profile/desktop_dev --build=missing -if=build/desktop_dev/conan-dependencies
      
    - name: CMake configure step
      run: |
        cd apps/TermGraphApp/
        cmake --preset desktop_dev ./

    - name: Cmake build
      run: |
        cd apps/TermGraphApp/
        cmake --build --preset desktop_dev
