name: Build desktop_release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Ninja
      run: sudo apt install ninja-build

    - name: Install Conan package manager
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'pip_requirements.txt'
    - run: pip install -r pip_requirements.txt

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '6.4.1'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - name: Conan install dependencies
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: conan install . --profile conanfiles/profile/desktop_release --build=missing -if=build/desktop_release/conan-dependencies
      
    - name: CMake configure
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --preset desktop_release ./

    - name: Cmake build
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --build --preset desktop_release

    - name: CTest
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: ctest --preset desktop_release
