name: Build desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.4.1
  QT_ROOT: ${{ github.workspace }}/Qt

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        build_profile: [desktop_dev, desktop_release]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: sudo apt install ninja-build

    - name: Install Conan package manager
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'pip_requirements.txt'
    - run: pip install -r pip_requirements.txt

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: ${{ env.QT_VERSION }}
        dir: ${{ github.workspace }}
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - name: Conan install dependencies
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: conan install . --profile conanfiles/profile/${{ matrix.build_profile }} --build=missing -if=build/${{ matrix.build_profile }}/conan-dependencies

    - name: CMake configure
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --preset ${{ matrix.build_profile }} ./

    - name: Cmake build
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --build --preset ${{ matrix.build_profile }}

    - name: CTest
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: ctest --preset ${{ matrix.build_profile }}
