name: Frontend build, deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

env:
  QT_VERSION: 6.4.2
  WASM_VERSION: 3.1.14
  QT_ROOT: ${{ github.workspace }}/Qt

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        build_profile: [wasm_release]

    concurrency:
      group: AppBuild-${{ github.workflow }}-${{ github.ref }}-${{ matrix.build_profile }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: sudo apt install ninja-build

    - name: Install Conan package manager
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'pip_requirements.txt'
    - run: pip install -r pip_requirements.txt

    - name: Install Wasm
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.WASM_VERSION }}
        actions-cache-folder: 'emsdk-cache'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: ${{ env.QT_VERSION }}
        dir: ${{ github.workspace }}
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qt5compat qtshadertools'
        archives: 'qttranslations qttools qtsvg qtdeclarative qtbase icu'
        cache: true

    - name: Cache Multithread qt wasm
      id: cache-mt-wasm
      uses: actions/cache@v3
      with:
        key: ${{ env.QT_VERSION }}-wasm_32_mt
        path: ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/wasm_32_mt

    - if: ${{ steps.cache-mt-wasm.outputs.cache-hit != 'true' }}
      name: Build multithread Qt wasm
      working-directory: ${{github.workspace}}/tools/build_qt_wasm/build
      run: python ./build.py

    - name: Conan install dependencies
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: conan install . --profile conanfiles/profile/${{ matrix.build_profile }} --build=missing -if=build/${{ matrix.build_profile }}/conan-dependencies

    - name: CMake configure
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --preset ${{ matrix.build_profile }} ./

    - name: Cmake build
      working-directory: ${{github.workspace}}/apps/TermGraphApp
      run: cmake --build --preset ${{ matrix.build_profile }}

    - name: Make deploy folder
      working-directory: ${{github.workspace}}/apps/TermGraphApp/build/wasm_release
      run: |
        mkdir deploy
        cp qtloader.js         deploy/
        cp qtlogo.svg          deploy/
        cp TermGraph.js        deploy/
        cp TermGraph.wasm      deploy/
        cp TermGraph.worker.js deploy/
        cp TermGraph.html      deploy/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{github.workspace}}/apps/TermGraphApp/build/wasm_release/deploy

  deploy:
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
